function(run_debugger_subprocess IS_BREAKPOINT)
    get_cmake_property(VARIABLE_NAMES VARIABLES)
    list(SORT VARIABLE_NAMES)
    set(DEBUGGER_STATE "")
    foreach (VARIABLE_NAME ${VARIABLE_NAMES})
        string(APPEND DEBUGGER_STATE "${VARIABLE_NAME}=${${VARIABLE_NAME}}|")
    endforeach()
    execute_process(COMMAND ${DEBUGGER_SUBPROCESS_PATH} "${DEBUGGER_STATE}" ${IS_BREAKPOINT})
endfunction()
